// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hctzdleyfndqmhmouoqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjdHpkbGV5Zm5kcW1obW91b3FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDA3MDAsImV4cCI6MjA3MDExNjcwMH0.vGXMyyV0pWzMQADetFbrvAZGFMNBiXd8P71YT_sq67I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});